### ISSUE TITLE
为什么代码不缩进呢？

### ISSUE THREAD

**Issue by pengweb** [foreachsam/hexo-theme-monogatari#1]
我用了这个主题，但是我的代码却不缩进，这是为什么呢？？能帮忙解答一下吗？谢谢

**Comment by foreachsam** [comment]
我看了你這一頁
http://pengweb.github.io/2016/04/07/Express-%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/

我也不確定你為啥不能縮格，不過看你代碼那部份，parse出來的結果好像怪怪的

我這裡的這一頁，是可以的，我在我的本機，也重新測試過，是ok的，會縮格

https://foreachsam.github.io/blog-lang-php/article/read/composer/scripts/

那一頁的markdown原始碼如下(只是其中代碼的那部份)

```
{
&nbsp;&nbsp;&nbsp;&nbsp;"scripts": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"serve": "php -S localhost:8080 -t public/"
&nbsp;&nbsp;&nbsp;&nbsp;}  
}
```

**Comment by pengweb** [comment]
@foreachsam 应该是我改了什么文件，原主题确实没有问题，我在弄一下 谢谢

**Comment by foreachsam** [comment]
我看了你這一頁的原始碼
https://github.com/pengweb/BLOG/blob/master/source/_posts/Express-%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0.md

某段代碼
你開頭的第一行
「```js var express = require('express');」
然後最後一行「})```」

開頭「```js」 和結尾「```」應該是放在獨立的一行，才不會造成你parse出來的版面錯亂。
http://pengweb.github.io/2016/04/07/Express-%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/

不過上面這個問題好像跟沒有縮格這件事無關的樣子，我還沒測試你的設定，先提出上面看到的。 

我要先忙其他的事，暫離 :-)

**Comment by pengweb** [comment]
@foreachsam 非常非常感谢，我找到原因了，是样式有个地方写的不对，再次感谢
